from src.SportsAPIClient import SportsAPIClient

class IntegrationLayer:
    
    # also need caching trying to save/check stale data for I'll work on this later..... next wednesday or smth
    async def get_player_and_stats(player_name):
        # get player profile through last name and go through the list of player 
        
        # if first name match exists, go with that else ask back user for confirming
        
        # get player list of teams and team_id player has played and find which one user wants
        
        # get the league of which team is associated with
        
        # finally get the stupid stats
        return ""